default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: cobra
  password:
  host: localhost
  min_messages: warning

development:
  <<: *default
  database: cobra

test:
  <<: *default
  database: cobra_test

production:
  <<: *default
  database: cobra
